baseurl: ''
description: 使用Python自研的博客系统
exclude:
- blog_manager.py
- blog_config.yaml
- requirements.txt
- homework.py
- README.md
- .git
highlighter: rouge
markdown: kramdown
minima:
  date_format: '%Y-%m-%d'
  social_links:
    github: ''
plugins:
- jekyll-feed
- jekyll-seo-tag
theme: minima
title: 我的博客
url: ''
